"""
Shared constants for the application.
"""

class ServerPallette:
    """ Color for server"""
    COLOR = [
        "#33FF57",  # Green
        "#F333FF",  # Magenta
        "#3357FF",  # Blue
        "#FF8C33",  # Orange
        "#FF33A1",  # Pink
        "#F3FF33",  # Yellow
        "#33FF8C",  # Mint
        "#FF5733",  # Red-Orange
        "#33FFF3",  # Cyan
        "#A133FF",  # Purple
        "#FF3333",  # Bright Red
        "#33FFDA",  # Aqua
        "#FFB833",  # Amber
        "#8C33FF",  # Violet
        "#33A1FF",  # Sky Blue
        "#33FFB8",  # Spearmint
        "#FFD133",  # Golden Yellow
        "#33FFA5",  # Light Green
        "#C70039",  # Deep Red
        "#00B8FF",  # Electric Blue
    ]

class AppCacheTimeout:
    """ All Cache timeout value"""
    INFO_CACHE_TTL = 60
    XML_CACHE_TTL = 3600 # 1 hour
    DONT_DISPLAY_DISK_USAGE = 50

class AppInfo:
    """Define app data"""
    name = "virtui-manager"
    namecase = "VirtUI Manager"
    version = "1.1.6"

class VmAction:
    """Defines constants for VM action types."""
    START = "start"
    STOP = "stop"
    FORCE_OFF = "force_off"
    PAUSE = "pause"
    RESUME = "resume"
    DELETE = "delete"

class VmStatus:
    """Defines constants for VM status filters."""
    DEFAULT = "default"
    RUNNING = "running"
    PAUSED = "paused"
    PMSUSPENDED = "pmsuspended"
    BLOCKED = "blocked"
    STOPPED = "stopped"
    SELECTED = "selected"

class ButtonLabels:
    """Constants for button labels"""
    START = "Start"
    SHUTDOWN = "Shutdown"
    FORCE_OFF = "Force Off"
    PAUSE = "Pause"
    RESUME = "Resume"
    CONFIGURE = "Configure"
    WEB_CONSOLE = "Web Console"
    CONNECT = "Connect"
    SNAPSHOT = "Snapshot"
    RESTORE_SNAPSHOT = "Restore Snapshot"
    DELETE_SNAPSHOT = "Del Snapshot"
    DELETE = "Delete"
    CLONE = "! Clone !"
    MIGRATION = "! Migration !"
    VIEW_XML = "View XML"
    RENAME = "Rename"
    SELECT_SERVER = "[b][#FFD700]S[/][/]elect Servers"
    MANAGE_SERVERS = "Servers [b][#FFD700]L[/][/]ist"
    SERVER_PREFERENCES = "Server Prefs"
    FILTER_VM = "[b][#FFD700]F[/][/]ilter VM"
    VIEW_LOG = "Log"
    BULK_CMD = "[b][#FFD700]B[/][/]ulk CMD"
    PATTERN_SELECT = "[b][#FFD700]P[/][/]attern Sel"
    CONFIG = "Config"
    PREVIOUS_PAGE = "Previous Page"
    NEXT_PAGE = "Next Page"
    YES = "Yes"
    NO = "No"
    CANCEL = "Cancel"
    CREATE = "Create"
    CHANGE = "Change"
    STOP = "Stop"
    CLOSE = "Close"
    CREATE_OVERLAY = "New Overlay"
    COMMIT_DISK = "Commit Disk"
    DISCARD_OVERLAY = "Discard Overlay"
    SNAP_OVERLAY_HELP = "Help"
    COMPACT_VIEW = "Compact"


class TabTitles:
    """Constants for tab titles"""
    MANAGE = "Manage"
    OTHER = "Other"
    SNAPSHOT = "Snapshot"
    SNAPSHOTS = "Snapshots"
    OVERLAY = "Overlay"
    SNAP_OVER_UPDATE = "Updating Data..."

class StatusText:
    """Constants for status text"""
    STOPPED = "Stopped"
    RUNNING = "Running"
    PAUSED = "Paused"
    PMSUSPENDED = "PMSuspended"
    BLOCKED = "Blocked"
    LOADING = "Loading"

class SparklineLabels:
    """Constants for sparkline labels"""
    DISK_RW = "Disk R/W {read:.2f}/{write:.2f} MB/s"
    NET_RX_TX = "Net Rx/Tx {rx:.2f}/{tx:.2f} MB/s"
    VCPU = "{cpu} VCPU"
    MEMORY_GB = "{mem} Gb"

class ErrorMessages:
    """Constants for error messages"""
    R_VIEWER_NOT_FOUND = "Remote viewer command not found. Please ensure it is installed."
    CANNOT_OPEN_DISPLAY = "Could not open display. Ensure you are in a graphical session."
    HARD_STOP_WARNING = "This is a hard stop, like unplugging the power cord."
    MIGRATION_LOCALHOST_NOT_SUPPORTED = "Migration from localhost (qemu:///system) is not supported.\nA full remote URI (e.g., qemu+ssh://user@host/system) is required."
    NO_DESTINATION_SERVERS = "No destination servers available."
    DIFFERENT_SOURCE_HOSTS = "Cannot migrate VMs from different source hosts at the same time."
    MIXED_VM_STATES = "Cannot migrate running/paused and stopped VMs at the same time."
    WEBSOCKIFY_NOT_FOUND = "websockify is not installed. 'Web Console' button will be disabled."
    NOVNC_NOT_FOUND = "novnc is not installed. 'Web Console' button will be disabled."
    FAILED_TO_OPEN_CONNECTION = "Failed to open connection to [b]{uri}[/b]"
    NOT_CONNECTED_TO_ANY_SERVER = "Not connected to any server."
    COULD_NOT_CONNECT_TO_SERVER = "Could not connect to {uri}"
    NO_ACTION_TYPE_BULK_MODAL = "No action type received from bulk action modal."
    VM_NOT_FOUND_FOR_EDITING = "Could not find any of the selected VMs for editing."
    VMS_MUST_BE_STOPPED_FOR_BULK_EDITING = "All VMs must be stopped for bulk editing. Running VMs: {running_vms}"
    COULD_NOT_LOAD_DETAILS_FOR_REFERENCE_VM = "Could not load details for reference VM."
    SERVER_DISCONNECTED_AUTOCONNECT_DISABLED = "Server(s) {names} disconnected and autoconnect disabled due to connection failures."
    NO_ACTIVE_SERVERS = "No active servers."
    NO_VMS_IN_CACHE = "No VMs found in cache. Try refreshing first."
    NO_VMS_SELECTED = "No VMs selected."
    ERROR_FETCHING_VM_DATA = "Error fetching VM data: {error}"
    ERROR_DURING_INITIAL_CACHE_LOADING = "Error during initial cache loading: {error}"
    ERROR_ON_VM_DURING_ACTION = "Error on VM [b]{vm_name}[/b] during '{action}': {error}"
    FATAL_ERROR_BULK_ACTION = "A fatal error occurred during bulk action: {error}"
    VM_INFO_ERROR = "Error getting info for VM '{vm_name}': {error}"
    VM_NOT_FOUND_BY_ID = "Could not find VM with ID [b]{vm_id}[/b]"
    BULK_EDIT_PREP_ERROR = "Error preparing bulk edit: {error}"
    SERVER_CONNECTION_ERROR = "Server [b]{server_name}[/b]: {error_msg}"
    SERVER_FAILED_TO_CONNECT = "Failed to connect to [b]{server_name}[/b]: {error_msg}"
    BULK_ACTION_FAILED_TEMPLATE = "Bulk action [b]{action_type}[/b] failed for {count} VMs."
    PREFERENCES_LAUNCH_ERROR = "Error launching preferences: {error}"
    BULK_ACTION_VM_NAMES_RETRIEVAL_FAILED = "Could not retrieve names for selected VMs."
    VM_CLONE_FAILED_TEMPLATE = "Failed to clone to: {vm_names}"
    NO_SUITABLE_DISKS_FOR_OVERLAY = "No suitable disks found for overlay."
    OVERLAY_NAME_EMPTY_AFTER_SANITIZATION = "Overlay volume name cannot be empty after sanitization."
    ERROR_CREATING_OVERLAY_TEMPLATE = "Error creating overlay: {error}"
    ERROR_PREPARING_OVERLAY_CREATION_TEMPLATE = "Error preparing overlay creation: {error}"
    NO_OVERLAY_DISKS_FOUND = "No overlay disks found."
    ERROR_DISCARDING_OVERLAY_TEMPLATE = "Error discarding overlay: {error}"
    ERROR_PREPARING_DISCARD_OVERLAY_TEMPLATE = "Error preparing discard overlay: {error}"
    NO_DISKS_FOUND_TO_COMMIT = "No disks found to commit."
    ERROR_COMMITTING_DISK_TEMPLATE = "Error committing disk: {error}"
    ERROR_PREPARING_COMMIT_TEMPLATE = "Error preparing commit: {error}"
    INVALID_XML_TEMPLATE = "Invalid XML for '[b]{vm_name}[/b]': {error}. Your changes have been discarded."
    ERROR_GETTING_XML_TEMPLATE = "Error getting XML for VM [b]{vm_name}[/b]: {error}"
    UNEXPECTED_ERROR_OCCURRED_TEMPLATE = "An unexpected error occurred: {error}"
    CONNECTION_INFO_NOT_AVAILABLE = "Connection info not available for this VM."
    REMOTE_VIEWER_FAILED_TO_START_TEMPLATE = "{viewer} failed to start for {domain_name}: {error}"
    ERROR_GETTING_VM_DETAILS_TEMPLATE = "Error getting VM details for [b]{vm_name}[/b]: {error}"
    UNEXPECTED_ERROR_CONNECTING = "An unexpected error occurred while trying to connect."
    ERROR_CHECKING_WEB_CONSOLE_STATUS_TEMPLATE = "Error checking web console status for [b]{vm_name}[/b]: {error}"
    SNAPSHOT_ERROR_TEMPLATE = "Snapshot error for [b]{vm_name}[/b]: {error}"
    NO_SNAPSHOTS_TO_RESTORE = "No snapshots to restore."
    ERROR_FETCHING_SNAPSHOTS_TEMPLATE = "Error fetching snapshots: {error}"
    NO_SNAPSHOTS_TO_DELETE = "No snapshots to delete."
    ERROR_DELETING_VM_TEMPLATE = "Error deleting VM '{vm_name}': {error}"
    VM_NAME_EMPTY_AFTER_SANITIZATION = "VM name cannot be empty after sanitization."
    ERROR_RENAMING_VM_TEMPLATE = "Error renaming VM [b]{vm_name}[/b]: {error}"
    VM_NOT_FOUND_ON_ACTIVE_SERVER_TEMPLATE = "VM [b]{vm_name}[/b] with internal ID [b]{uuid}[/b] not found on any active server."
    ERROR_GETTING_ID_TEMPLATE = "Error getting ID for [b]{vm_name}[/b]: {error}"
    SELECT_AT_LEAST_TWO_SERVERS_FOR_MIGRATION = "Please select at least two servers in 'Select Servers' to enable migration."
    SELECTED_VM_NOT_FOUND_ON_ACTIVE_SERVER_TEMPLATE = "Selected VM with ID [b]{uuid}[/b] not found on any active server."
    ERROR_GETTING_EXISTING_VM_NAMES_TEMPLATE = "Error getting existing VM names: {error}"
    WEBCONSOLE_VNC_ONLY = "Web console only supports VNC graphics."
    COULD_NOT_DETERMINE_VNC_PORT = "Could not determine VNC port for the VM."
    FAILED_TO_START_WEBCONSOLE_TEMPLATE = "Failed to start web console: {error}"
    NO_FREE_WEBCONSOLE_PORT = "Could not find a free port for the web console (all ports in range used by other sessions)."
    REMOTE_KEY_GENERATION_FAILED = "Remote key generation failed. Falling back to insecure ws connection."
    FAILED_TO_START_REMOTE_WEBSOCKIFY_TEMPLATE = "Failed to start remote websockify for [b]{vm_name}[/b]. Check logs."
    REMOTE_WEBCONSOLE_CRASHED_TEMPLATE = "Remote web console process for [b]{vm_name}[/b] failed to start or crashed. Check remote logs."
    NO_FREE_LOCAL_PORT_FOR_SSH_TUNNEL = "Could not find a free local port for SSH tunnel."
    FAILED_TO_CREATE_SSH_TUNNEL_TEMPLATE = "Failed to create SSH tunnel: {error}"
    SSH_COMMAND_NOT_FOUND = "SSH command not found. Cannot create tunnel."
    FAILED_TO_CREATE_SSH_TUNNEL_GENERIC = "Failed to create SSH tunnel..."
    PLEASE_SELECT_ACTION = "Please select an action."
    ERROR_SAVING_CONFIGURATION_TEMPLATE = "Error saving configuration: {e}"
    VALIDATION_ERROR_TEMPLATE = "Validation error: {error}"
    INVALID_FORMAT_TEMPLATE = "Invalid format: {error}"
    INVALID_NODESET_SYNTAX_TEMPLATE = "Invalid nodeset syntax: {nodeset}"
    CREATE_DISK_REQUIRED_FIELDS = "Pool, Volume Name, and Size are required to create a new disk."
    DISK_IMAGE_PATH_REQUIRED = "Path to disk image is required."
    POOL_NAME_REQUIRED = "Pool name is required."
    TARGET_PATH_REQUIRED_FOR_DIR = "Target Path is required for `dir` type."
    NETFS_FIELDS_REQUIRED = "For `netfs`, all fields are required."
    NAME_AND_SIZE_REQUIRED = "Name and size are required."
    SIZE_MUST_BE_INTEGER = "Size must be an integer."
    DEST_POOL_AND_NAME_REQUIRED = "Destination pool and new name are required."
    NAME_PATH_FORMAT_REQUIRED = "Name, path, and format are required. Ensure a file is selected."
    ERROR_CREATING_STORAGE_POOL_TEMPLATE = "Error creating storage pool: {error}"
    SELECT_DESTINATION_SERVER = "Please select a destination server."
    RUN_COMPATIBILITY_CHECK_FIRST = "Please run compatibility check first."
    MIGRATION_COMPATIBILITY_ERRORS = "Cannot start migration due to compatibility errors."
    NETWORK_NOT_FOUND_TEMPLATE = "Network '{network}' not found. Please select an available network."
    SELECT_NETWORK = "Please select a network."
    FORWARD_DEVICE_NOT_FOUND_TEMPLATE = "Forward device '{device}' not found on host."
    ERROR_GETTING_HOST_INTERFACES_TEMPLATE = "Error getting host interfaces: {error}"
    INVALID_NETWORK_NAME_TEMPLATE = "Invalid Network Name: {error}"
    INVALID_CUSTOM_DNS_DOMAIN_TEMPLATE = "Invalid Custom DNS Domain: {error}"
    NETWORK_NAME_REQUIRED = "Network Name cannot be empty."
    DHCP_IPS_NOT_IN_NETWORK_TEMPLATE = "DHCP IPs are not in the network {network}"
    DHCP_START_BEFORE_END = "DHCP start IP must be before the end IP."
    INVALID_IP_OR_NETWORK_TEMPLATE = "Invalid IP address or network: {error}"
    DHCP_REQUIRES_IP = "DHCP cannot be enabled without an IP network."
    SUBNET_OVERLAPS_TEMPLATE = "Subnet {subnet} overlaps with an existing network."
    ERROR_CREATING_NETWORK_TEMPLATE = "Error creating network: {error}"
    ERROR_UPDATING_NETWORK_TEMPLATE = "Error updating network: {error}"
    NETWORK_NOT_FOUND_TEMPLATE_2 = "Network '{network}' not found. Please select an available network."
    VM_NAME_ALREADY_EXISTS_TEMPLATE = "A VM with the name '{vm_name}' already exists. Please choose a different name."
    ERROR_CHECKING_VM_NAME_TEMPLATE = "Error checking VM name: {error}"
    PLEASE_SELECT_VALID_STORAGE_POOL = "Please select a valid storage pool."
    ISO_VOLUME_NOT_FOUND_TEMPLATE = "Selected ISO volume does not exist: {iso_url}"
    SELECT_VALID_ISO_VOLUME = "Please select a valid ISO volume from the storage pool."
    INVALID_EXPERT_SETTINGS = "Invalid input for expert settings. Using defaults."
    MEMORY_RANGE_ERROR = "Memory must be between 1 and 8192 GB."
    CPU_RANGE_ERROR = "CPU count must be between 1 and 768."
    DISK_SIZE_RANGE_ERROR = "Disk size must be between 1 and 10000 GB."
    STORAGE_POOL_NOT_ACTIVE_TEMPLATE = "Storage pool '{pool_name}' is not active. Please activate it first."
    ERROR_ACCESSING_STORAGE_POOL_TEMPLATE = "Error accessing storage pool '{pool_name}': {error}"
    CUSTOM_ISO_PATH_NOT_EXIST_TEMPLATE = "Custom ISO path does not exist: {path}"
    CUSTOM_ISO_NOT_FILE_TEMPLATE = "Custom ISO path is not a file: {path}"
    CHECKSUM_MISSING = "Checksum validation enabled but no checksum provided"
    CHECKSUM_VALIDATION_FAILED = "Checksum validation failed!"
    NO_ISO_URL_SPECIFIED = "No ISO URL specified for provisioning"
    COULD_NOT_GET_VM_DETAILS_TEMPLATE = "Could not get details for {vm_name}"
    FAILED_TO_START_VM_OR_VIEWER_TEMPLATE = "Failed to start VM or viewer: {error}"
    PROVISIONING_FAILED_TEMPLATE = "Provisioning failed: {error}"
    FAILED_TO_FETCH_ISO_VOLUMES_TEMPLATE = "Failed to fetch ISO volumes from {pool_name}: {error}"
    FAILED_TO_FETCH_ISOS_TEMPLATE = "Failed to fetch ISOs: {error}"
    VM_NAME_CANNOT_BE_EMPTY = "VM name cannot be empty."


class DialogMessages:
    """Constants for dialog messages"""
    DELETE_VM_CONFIRMATION = "Are you sure you want to delete '{name}'?"
    DELETE_SNAPSHOT_CONFIRMATION = "Are you sure you want to delete snapshot '{name}'?"
    DELETE_SNAPSHOTS_AND_RENAME = "VM has {count} snapshot(s). To rename, they must be deleted.\nDelete snapshots and continue?"
    EXPERIMENTAL = "Experimental Feature! Still contains bugs, fix in progress. You have been informed"


class QuickMessages:
    """Constants for quick messages"""
    REMOTE_VIEWER_SELECTED = "The remove viewer {viewer} has been selected."
    VM_DATA_LOADED = "VM data loaded. Displaying VMs..."
    FILTER_RUNNING_VMS = "Filter: Running VMs"
    FILTER_ALL_VMS = "Filter: All VMs"
    ALL_VMS_UNSELECTED = "All VMs unselected."
    CACHING_VM_STATE = "Caching VM state for: {vms_list}"


class WarningMessages:
    """Constants for warning messages"""
    COMPACT_VIEW_LOCKED = "Compact view is locked during bulk operations."
    VMS_PER_PAGE_PERFORMANCE_WARNING = "Displaying [b]{vms_per_page}[/b] VMs per page. CPU usage may increase; 9 is recommended for optimal performance."
    VM_NOT_PAUSABLE = "VM '{vm_name}' is not in a pausable state."
    LIBVIRT_XML_NO_EFFECTIVE_CHANGE = "VM [b]{vm_name}[/b]: Libvirt accepted the XML but the configuration remains unchanged. Your changes may have been ignored or normalized away."
    NO_REMOTE_VIEWER_SELECTED = "No remote viewer selected. Auto-detection will be used."


class SuccessMessages:
    """Constants for success messages"""
    REMOTE_VIEWER_SELECTED = "The remove viewer {viewer} has been selected."
    CONNECTED_TO_SERVER = "Connected to [b]{uri}[/b]"
    STATS_LOGGING_DISABLED = "Statistics logging and monitoring disabled."
    STATS_LOGGING_ENABLED = "Statistics logging and monitoring enabled (every 10s)."
    CONFIG_UPDATED = "Configuration updated."
    VMS_SELECTED_BY_PATTERN = "Selected {count} VMs matching pattern."
    TERMINAL_COPY_HINT = "In some Terminal use [b]Shift[/b] key while selecting text with the mouse to copy it."
    NO_SERVERS_CONFIGURED = "No servers configured. Please add one via 'Servers List'."
    LOG_LEVEL_CHANGED = "Log level changed to {level}"
    BULK_ACTION_SUCCESS_TEMPLATE = "Bulk action [b]{action_type}[/b] successful for {count} VMs."
    SERVER_CONNECTED = "Connected to [b]{name}[/b]"
    INPUT_SANITIZED = "Input sanitized: '{original_input}' changed to '{sanitized_input}'"
    OVERLAY_CREATED = "Overlay [b]{overlay_name}[/b] created and attached."
    OVERLAY_DISCARDED = "Overlay for [b]{target_disk}[/b] discarded and reverted to base image."
    DISK_COMMITTED = "Disk changes committed successfully."
    VM_CONFIG_UPDATED = "VM [b]{vm_name}[/b] configuration updated successfully."
    NO_XML_CHANGES = "No changes made to the XML configuration."
    SNAPSHOT_CREATED = "Snapshot [b]{snapshot_name}[/b] created successfully."
    SNAPSHOT_RESTORED = "Restored to snapshot [b]{snapshot_name}[/b] successfully."
    SNAPSHOT_DELETED = "Snapshot [b]{snapshot_name}[/b] deleted successfully."
    VM_DELETED = "VM '{vm_name}' deleted successfully."
    VM_RENAMED = "VM '{old_name}' renamed to '{new_name}' successfully."
    VM_RENAME_CANCELLED = "VM rename cancelled."
    VM_RENAME_NO_CHANGE = "New VM name is the same as the old name. No rename performed."
    VM_CLONED = "Successfully cloned to: {vm_names}"
    WEBCONSOLE_STOPPED = "Web console stopped."
    REMOTE_USER_CERT_FOUND = "Remote user cert/key found, using secure wss connection."
    REMOTE_SYSTEM_CERT_FOUND = "Remote system cert/key found, using secure wss connection."
    NO_REMOTE_CERT_FOUND_GENERATING = "No remote cert/key found. Attempting to generate in system directory..."
    NO_REMOTE_CERT_CHECK_INSECURE = "Could not check for remote cert/key, using insecure ws connection."
    REMOTE_CONNECTION_SSH_TUNNEL_SETUP = "Remote connection detected. Setting up SSH tunnel..."
    LOCAL_CERT_FOUND = "Found cert/key, using secure wss connection."
    ALL_CACHES_CLEARED = "All caches cleared"
    CONFIGURATION_SAVED = "Configuration saved successfully."
    STORAGE_POOL_CREATED_TEMPLATE = "Storage pool '{name}' created and started."
    NETWORK_CREATED_TEMPLATE = "Network {name} created successfully."
    NETWORK_UPDATED_TEMPLATE = "Network {name} updated successfully."
    VM_NAME_SANITIZED_TEMPLATE = "VM name sanitized: '{original}' -> '{sanitized}'"
    VM_STARTED_TEMPLATE = "VM '{vm_name}' started."
    REMOTE_VIEWER_STARTED_TEMPLATE = "Remote viewer {viewer} started for {vm_name}"
    VM_DEFINED_CONFIGURE_TEMPLATE = "VM '{vm_name}' defined. Please configure and start it."
    VM_CREATED_SUCCESSFULLY_TEMPLATE = "VM '{vm_name}' created successfully!"


class ProgressMessages:
    """Constants for success messages"""
    CONNECTING_TO_SERVER = "Connecting to [b]{uri}[/b]..."
    CONFIG_UPDATED_REFRESHING_VM_LIST = "Configuration updated. Refreshing VM list..."
    LOADING_VM_DATA_FROM_REMOTE_SERVERS = "Loading VM data from remote server(s)..."
